version: "2.1"

services:
  shell:
    image: hyperledger/sawtooth-all:1.0
    container_name: sawtooth-shell-default
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""

  validator:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator-default
    expose:
      - 4004
      - 8800
    ports:
      - "4004:4004"
      - "8800:8800"
    command: "bash -c \"\
        sawadm keygen --force && \
        sawtooth-validator -v \
          --bind network:tcp://eth0:8800 \
          --bind component:tcp://eth0:4004 \
          --endpoint tcp://10.0.1.12:8800 \
          --peers tcp://10.0.1.10:8800,tcp://10.0.1.11:8800
    \""
    depends_on:
      - shell
    stop_signal: SIGKILL

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api-default
    expose:
      - 4004
      - 8008
    ports:
      - "8008:8008"
    depends_on:
      - validator
    command: sawtooth-rest-api --connect tcp://validator:4004 --bind rest-api:8008
    stop_signal: SIGKILL

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp-default
    expose:
      - 4004
    depends_on:
      - validator
    command: settings-tp -C tcp://validator:4004
    stop_signal: SIGKILL

  poet-validator-registry-tp:
    image: hyperledger/sawtooth-poet-validator-registry-tp:1.0
    container_name: sawtooth-poet-validator-registry-tp
    expose:
      - 4004
    depends_on:
      - validator
    command: poet-validator-registry-tp -C tcp://validator:4004
    environment:
      PYTHONPATH: /project/sawtooth-core/consensus/poet/common
    stop_signal: SIGKILL

  intkey-tp:
    image: hyperledger/sawtooth-intkey-tp-python:1.0
    container_name: sawtooth-intkey-tp-python-default
    expose:
      - 4004
    depends_on:
      - validator
    command: intkey-tp-python -C tcp://validator:4004
    stop_signal: SIGKILL